package SysTicket::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

my $database_filename = SysTicket->config->{database}->{filename};
my $dsn = "dbi:SQLite:$database_filename";

__PACKAGE__->config(
    schema_class => 'SysTicket::Schema',
    
    connect_info => {
        dsn => $dsn,
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

SysTicket::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SysTicket>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SysTicket::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Ionel

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
